import type {
  Activity,
  Client,
  Document,
  Matter,
  Message,
  Organization,
  ReferenceItem,
  Task,
  User,
} from './domain';
export const organization: Organization = {
  id: 'org-lex',
  name: 'Meridian Legal',
  initials: 'ML',
  timeZone: 'Europe/London',
  currency: 'GBP',
};
export const users: User[] = [
  {
    id: 'olivia',
    organizationId: 'org-lex',
    name: 'Olivia Bennett',
    initials: 'OB',
    role: 'lawyer',
    title: 'Partner · Corporate & M&A',
    email: 'olivia@meridian.example',
    timeZone: 'Europe/London',
  },
  {
    id: 'lucas',
    organizationId: 'org-lex',
    name: 'Lucas Moreau',
    initials: 'LM',
    role: 'lawyer',
    title: 'Counsel · Intellectual Property',
    email: 'lucas@meridian.example',
    timeZone: 'Europe/Paris',
  },
  {
    id: 'maya',
    organizationId: 'org-lex',
    name: 'Maya Chen',
    initials: 'MC',
    role: 'lawyer',
    title: 'Counsel · Commercial',
    email: 'maya@meridian.example',
    timeZone: 'Asia/Singapore',
  },
  {
    id: 'ethan',
    organizationId: 'org-lex',
    name: 'Ethan Brooks',
    initials: 'EB',
    role: 'paralegal',
    title: 'Paralegal · Transactions',
    email: 'ethan@meridian.example',
    timeZone: 'America/New_York',
  },
  {
    id: 'sophie',
    organizationId: 'org-lex',
    name: 'Sophie Laurent',
    initials: 'SL',
    role: 'admin',
    title: 'Workspace administrator',
    email: 'sophie@meridian.example',
    timeZone: 'Europe/Paris',
  },
  {
    id: 'alex',
    organizationId: 'org-lex',
    name: 'Alex Morgan',
    initials: 'AM',
    role: 'client',
    title: 'General Counsel · Asteria Technologies',
    email: 'alex@asteria.example',
    timeZone: 'America/New_York',
    clientId: 'asteria',
  },
];
export const jurisdictions: ReferenceItem[] = [
  { id: 'ew', name: 'England & Wales' },
  { id: 'ny', name: 'United States / New York' },
  { id: 'eu', name: 'European Union' },
  { id: 'fr', name: 'France' },
  { id: 'it', name: 'Italy' },
  { id: 'es', name: 'Spain' },
  { id: 'de', name: 'Germany' },
  { id: 'sg', name: 'Singapore' },
];
export const practiceAreas: ReferenceItem[] = [
  { id: 'corporate', name: 'Corporate / M&A' },
  { id: 'ip', name: 'Intellectual Property' },
  { id: 'commercial', name: 'Commercial' },
  { id: 'employment', name: 'Employment' },
  { id: 'compliance', name: 'Regulatory & Compliance' },
  { id: 'disputes', name: 'Dispute Resolution' },
];
export const clients: Client[] = [
  {
    id: 'asteria',
    organizationId: 'org-lex',
    kind: 'organization',
    name: 'Asteria Technologies Ltd.',
    initials: 'AT',
    industry: 'Technology',
    country: 'United Kingdom',
    contact: 'Alex Morgan',
    email: 'alex@asteria.example',
    since: '2025-03-12',
  },
  {
    id: 'aurelia',
    organizationId: 'org-lex',
    kind: 'organization',
    name: 'Maison Aurelia SAS',
    initials: 'MA',
    industry: 'Consumer & retail',
    country: 'France',
    contact: 'Camille Dubois',
    email: 'camille@aurelia.example',
    since: '2025-08-04',
  },
  {
    id: 'northstar',
    organizationId: 'org-lex',
    kind: 'organization',
    name: 'Northstar Mobility GmbH',
    initials: 'NM',
    industry: 'Mobility',
    country: 'Germany',
    contact: 'Felix Weber',
    email: 'felix@northstar.example',
    since: '2026-01-19',
  },
  {
    id: 'veridian',
    organizationId: 'org-lex',
    kind: 'organization',
    name: 'Veridian Capital Partners',
    initials: 'VC',
    industry: 'Financial services',
    country: 'Singapore',
    contact: 'Amelia Tan',
    email: 'amelia@veridian.example',
    since: '2025-11-06',
  },
  {
    id: 'solstice',
    organizationId: 'org-lex',
    kind: 'organization',
    name: 'Solstice Labs Inc.',
    initials: 'SL',
    industry: 'Life sciences',
    country: 'United States',
    contact: 'Jordan Ellis',
    email: 'jordan@solstice.example',
    since: '2026-02-10',
  },
  {
    id: 'elena',
    organizationId: 'org-lex',
    kind: 'individual',
    name: 'Elena Rossi',
    initials: 'ER',
    industry: 'Independent design',
    country: 'Italy',
    contact: 'Elena Rossi',
    email: 'elena@design.example',
    since: '2026-07-08',
  },
];
export const matters: Matter[] = [
  {
    id: '1048',
    reference: 'LEX-2026-048',
    organizationId: 'org-lex',
    title: 'Northstar Acquisition',
    clientId: 'asteria',
    practiceAreaId: 'corporate',
    jurisdictionId: 'ew',
    leadCounselId: 'olivia',
    teamIds: ['olivia', 'ethan', 'maya'],
    status: 'in_review',
    priority: 'high',
    targetDate: '2026-10-14',
    createdAt: '2026-09-02T08:00:00Z',
    updatedAt: '2026-09-29T09:40:00Z',
    description:
      'Advise Asteria Technologies on its proposed acquisition of a mobility software business. Coordinate due diligence, review transaction documents and prepare a clear list of commercial decisions for the client. Scope and advice remain subject to professional review in the relevant jurisdiction.',
  },
  {
    id: '1047',
    reference: 'LEX-2026-047',
    organizationId: 'org-lex',
    title: 'EU Trademark Registration',
    clientId: 'aurelia',
    practiceAreaId: 'ip',
    jurisdictionId: 'eu',
    leadCounselId: 'lucas',
    teamIds: ['lucas', 'ethan'],
    status: 'client_action',
    priority: 'medium',
    targetDate: '2026-10-02',
    createdAt: '2026-09-05T10:00:00Z',
    updatedAt: '2026-09-29T08:20:00Z',
    description:
      'Coordinate the proposed trademark registration for the Aurelia Atelier collection. Review the client’s product categories and artwork, and prepare the filing pack for counsel review. Awaiting the final brand assets from the client.',
  },
  {
    id: '1046',
    reference: 'LEX-2026-046',
    organizationId: 'org-lex',
    title: 'Cross-border Distribution Agreement',
    clientId: 'northstar',
    practiceAreaId: 'commercial',
    jurisdictionId: 'de',
    leadCounselId: 'maya',
    teamIds: ['maya', 'olivia'],
    status: 'in_progress',
    priority: 'high',
    targetDate: '2026-10-05',
    createdAt: '2026-09-08T10:00:00Z',
    updatedAt: '2026-09-28T15:00:00Z',
    description:
      'Review the proposed distribution arrangement and coordinate comments from the commercial team. Focus on the agreed scope, delivery milestones and the allocation of responsibilities. Local counsel will review jurisdiction-specific points.',
  },
  {
    id: '1045',
    reference: 'LEX-2026-045',
    organizationId: 'org-lex',
    title: 'Investment Framework Review',
    clientId: 'veridian',
    practiceAreaId: 'compliance',
    jurisdictionId: 'sg',
    leadCounselId: 'maya',
    teamIds: ['maya', 'ethan'],
    status: 'open',
    priority: 'medium',
    targetDate: '2026-10-09',
    createdAt: '2026-09-20T10:00:00Z',
    updatedAt: '2026-09-28T11:00:00Z',
    description:
      'Organize a review of the proposed investment framework. Confirm the scope of work, collect the relevant policies and identify questions requiring specialist input. No regulatory conclusions have been recorded.',
  },
  {
    id: '1044',
    reference: 'LEX-2026-044',
    organizationId: 'org-lex',
    title: 'Executive Employment Terms',
    clientId: 'solstice',
    practiceAreaId: 'employment',
    jurisdictionId: 'ny',
    leadCounselId: 'olivia',
    teamIds: ['olivia'],
    status: 'in_progress',
    priority: 'medium',
    targetDate: '2026-10-07',
    createdAt: '2026-09-12T10:00:00Z',
    updatedAt: '2026-09-27T10:00:00Z',
    description:
      'Review draft executive employment terms against the client’s commercial instructions. Consolidate open questions for the HR team and coordinate review by New York counsel.',
  },
  {
    id: '1043',
    reference: 'LEX-2026-043',
    organizationId: 'org-lex',
    title: 'Software Licensing Portfolio',
    clientId: 'asteria',
    practiceAreaId: 'ip',
    jurisdictionId: 'ew',
    leadCounselId: 'lucas',
    teamIds: ['lucas', 'maya'],
    status: 'closed',
    priority: 'low',
    targetDate: '2026-09-25',
    createdAt: '2026-08-03T10:00:00Z',
    updatedAt: '2026-09-25T10:00:00Z',
    description:
      'Completed review of the client’s software licensing templates. The final review notes and agreed commercial positions have been shared with the client.',
  },
  {
    id: '1042',
    reference: 'LEX-2026-042',
    organizationId: 'org-lex',
    title: 'Design Rights Advisory',
    clientId: 'elena',
    practiceAreaId: 'ip',
    jurisdictionId: 'it',
    leadCounselId: 'lucas',
    teamIds: ['lucas'],
    status: 'on_hold',
    priority: 'low',
    targetDate: '2026-10-21',
    createdAt: '2026-09-10T10:00:00Z',
    updatedAt: '2026-09-24T10:00:00Z',
    description:
      'Review the proposed scope of design rights advice for a new furniture collection. Work is paused pending confirmation of the launch timetable and the final design materials.',
  },
];
export const documents: Document[] = [
  {
    id: 'd1',
    organizationId: 'org-lex',
    matterId: '1048',
    name: 'Share purchase agreement',
    type: 'Transaction agreement',
    uploadedBy: 'olivia',
    uploadedAt: '2026-09-29T09:40:00Z',
    version: 3,
    status: 'under_review',
    storage: { kind: 'demo' },
  },
  {
    id: 'd2',
    organizationId: 'org-lex',
    matterId: '1048',
    name: 'Due diligence findings',
    type: 'Review memorandum',
    uploadedBy: 'ethan',
    uploadedAt: '2026-09-28T12:00:00Z',
    version: 2,
    status: 'draft',
    storage: { kind: 'demo' },
  },
  {
    id: 'd3',
    organizationId: 'org-lex',
    matterId: '1047',
    name: 'Trademark application brief',
    type: 'Filing preparation',
    uploadedBy: 'lucas',
    uploadedAt: '2026-09-28T08:00:00Z',
    version: 1,
    status: 'draft',
    storage: { kind: 'demo' },
  },
  {
    id: 'd4',
    organizationId: 'org-lex',
    matterId: '1046',
    name: 'Distribution agreement',
    type: 'Commercial agreement',
    uploadedBy: 'maya',
    uploadedAt: '2026-09-27T15:00:00Z',
    version: 2,
    status: 'under_review',
    storage: { kind: 'demo' },
  },
  {
    id: 'd5',
    organizationId: 'org-lex',
    matterId: '1043',
    name: 'Licensing review notes',
    type: 'Review memorandum',
    uploadedBy: 'lucas',
    uploadedAt: '2026-09-25T10:00:00Z',
    version: 4,
    status: 'approved',
    storage: { kind: 'demo' },
  },
];
export const tasks: Task[] = [
  {
    id: 't1',
    organizationId: 'org-lex',
    matterId: '1048',
    title: 'Resolve outstanding due diligence questions',
    assigneeId: 'ethan',
    priority: 'high',
    dueDate: '2026-10-01',
    status: 'in_progress',
  },
  {
    id: 't2',
    organizationId: 'org-lex',
    matterId: '1047',
    title: 'Confirm final brand assets with the client',
    assigneeId: 'lucas',
    priority: 'high',
    dueDate: '2026-10-02',
    status: 'blocked',
  },
  {
    id: 't3',
    organizationId: 'org-lex',
    matterId: '1046',
    title: 'Consolidate distributor comments',
    assigneeId: 'maya',
    priority: 'medium',
    dueDate: '2026-10-03',
    status: 'todo',
  },
  {
    id: 't4',
    organizationId: 'org-lex',
    matterId: '1048',
    title: 'Prepare signing checklist',
    assigneeId: 'olivia',
    priority: 'medium',
    dueDate: '2026-10-08',
    status: 'todo',
  },
  {
    id: 't5',
    organizationId: 'org-lex',
    matterId: '1045',
    title: 'Confirm the scope of specialist review',
    assigneeId: 'maya',
    priority: 'medium',
    dueDate: '2026-10-06',
    status: 'todo',
  },
  {
    id: 't6',
    organizationId: 'org-lex',
    matterId: '1043',
    title: 'Share final licensing review with client',
    assigneeId: 'lucas',
    priority: 'low',
    dueDate: '2026-09-25',
    status: 'completed',
  },
];
export const messages: Message[] = [
  {
    id: 'msg1',
    organizationId: 'org-lex',
    matterId: '1048',
    authorId: 'olivia',
    text: 'The updated transaction draft is ready for your review. Please confirm the proposed completion timetable before we circulate the next version.',
    createdAt: '2026-09-29T09:20:00Z',
  },
  {
    id: 'msg2',
    organizationId: 'org-lex',
    matterId: '1048',
    authorId: 'alex',
    text: 'Thank you, Olivia. Our finance team is reviewing the timetable. I will share their comments tomorrow.',
    createdAt: '2026-09-29T10:00:00Z',
  },
  {
    id: 'msg3',
    organizationId: 'org-lex',
    matterId: '1046',
    authorId: 'maya',
    text: 'The commercial team’s comments have been consolidated. The remaining open points are listed in the review draft.',
    createdAt: '2026-09-28T15:00:00Z',
  },
];
export const activities: Activity[] = [
  {
    id: 'a1',
    organizationId: 'org-lex',
    matterId: '1048',
    actorId: 'olivia',
    createdAt: '2026-09-29T09:40:00Z',
    type: 'document_added',
    documentId: 'd1',
  },
  {
    id: 'a2',
    organizationId: 'org-lex',
    matterId: '1047',
    actorId: 'lucas',
    createdAt: '2026-09-29T08:20:00Z',
    type: 'status_changed',
    from: 'in_progress',
    to: 'client_action',
  },
  {
    id: 'a3',
    organizationId: 'org-lex',
    matterId: '1048',
    actorId: 'alex',
    createdAt: '2026-09-29T10:00:00Z',
    type: 'message_sent',
  },
  {
    id: 'a4',
    organizationId: 'org-lex',
    matterId: '1046',
    actorId: 'maya',
    createdAt: '2026-09-28T15:00:00Z',
    type: 'message_sent',
  },
  {
    id: 'a5',
    organizationId: 'org-lex',
    matterId: '1045',
    actorId: 'sophie',
    createdAt: '2026-09-28T11:00:00Z',
    type: 'counsel_assigned',
    userId: 'maya',
  },
  {
    id: 'a6',
    organizationId: 'org-lex',
    matterId: '1048',
    actorId: 'olivia',
    createdAt: '2026-09-02T08:00:00Z',
    type: 'matter_created',
  },
];
